### ISSUE TITLE
Port race condition fix

### ISSUE THREAD

**Issue by mourner** [fogleman/delaunay#1]
This fix should be ported — it's quite important for algorithm robustness: https://github.com/mapbox/delaunator/pull/25

@fogleman BTW thanks for the port — it looks great!

**Comment by fogleman** [comment]
@mourner Thanks, I'll take a look soon. I wonder if my floating point epsilon checks addressed this.

**Comment by fogleman** [comment]
Looks like my epsilon checks did address this, but I like this approach better - thanks!

**Comment by mourner** [comment]
@fogleman thanks! I think these are different issues that just happened to overlap for the tested examples — e.g. there could be a case that would corrupt halfedges integrity even with the epsilon check.

Numerical robustness may still be an issue (e.g. see https://github.com/mapbox/delaunator/issues/13) — I just decided not to address it in the library itself (and leave it up to users to e.g. round up the coordinates or multiply by a constant factor).
