### ISSUE TITLE
Port flat hull tracking

### ISSUE THREAD

**Issue by mourner** [fogleman/delaunay#2]
I'm very curious how the performance will look if we try porting https://github.com/mapbox/delaunator/pull/32 — might be a nice speedup.

**Comment by fogleman** [comment]
I'm curious too - just haven't had time yet. Might be able to today.

**Comment by fogleman** [comment]
Fixed in https://github.com/fogleman/delaunay/commit/1700afde92ce67e80a179cbf92ee5e4ec42a519e

**Comment by fogleman** [comment]
@mourner Doesn't seem to improve any of my benchmarks except for the circle. (2-3x faster in that case)
