### ISSUE TITLE
Tringles 

### ISSUE THREAD

**Issue by Konstantin8105** [fogleman/delaunay#3]
Could you clarify - how get list of triangles ?

**Comment by fogleman** [comment]
triangulation.Triangles is a list of indexes into the original points. Indexes 0, 1, 2 give you the first triangle, 3, 4, 5 the second, and so on...

**Comment by Konstantin8105** [comment]
@fogleman , thank you for clarification.

**Comment by Konstantin8105** [comment]
Thank you for good package

**Comment by Konstantin8105** [comment]
Could you clarify about elges? May I use halfegdes?

**Comment by fogleman** [comment]
Have you read this page? It explains it well, and the structures are the same for this library:

https://mapbox.github.io/delaunator/
